import type { Experience } from './types'

/** Work history. Exported 1:1 from the Payload `experiences` collection on 2026-09-12, minus
 * the one CMS row that recorded a formal education entry (BS Computer Science) rather than a
 * job — that fact already lives in `SITE.bio`, and the row was never rendered on its own by any
 * part of the redesigned site, so it isn't carried forward as content nothing displays. */
export const WORK_EXPERIENCE: Experience[] = [
  {
    slug: "freelance-software-engineer-freelance",
    title: "Freelance Software Engineer",
    company: "Freelance",
    location: "Malolos, Bulacan, PH",
    yearRange: "2024 - Present",
    dateRange: "Sept 2024 - Present",
    description: "Working as a freelance full-stack developer. My stack includes React, Next.js, TypeScript, Tailwind, PHP and PostgreSQL.",
    responsibilities: [],
    order: 1,
  },
  {
    slug: "full-stack-developer-stream-tv-cayman",
    title: "Full Stack Developer",
    company: "Stream.TV (Cayman)",
    location: "Georgetown, KY",
    yearRange: "2023 - 2024",
    dateRange: "July 2023 - Present",
    description: "I worked as a full-stack developer, managing and maintaining the backend using Laravel and MySQL. I also introduced NextJS on the new web application and docker deployment to AWS.",
    responsibilities: [],
    order: 2,
  },
  {
    slug: "senior-full-stack-developer-net-net-inc",
    title: "Senior Full Stack Developer",
    company: "NET(net) Inc.",
    location: "Georgetown, KY",
    yearRange: "2019 - 2023",
    dateRange: "January 2019 - July 2023",
    description: "I worked as full-stack developer, and started to work with the mobile project which introduced me to React Native and React",
    responsibilities: [],
    order: 3,
  },
  {
    slug: "net-developer-quad-it-solutions",
    title: ".NET Developer",
    company: "Quad IT Solutions",
    location: "Pasay, PH",
    yearRange: "2017 - 2018",
    dateRange: "October 2017 - January 2018",
    description: "I worked as a .NET Developer for 3 months, my main responsibilities are to fix existing bugs and implement new features.",
    responsibilities: [],
    order: 4,
  },
  {
    slug: "software-developer-egis-projects-philippines",
    title: "Software Developer",
    company: "Egis Projects Philippines",
    location: "Pasig, PH",
    yearRange: "2015 - 2017",
    dateRange: "November 2015 - August 2017",
    description: "I finally started working in the IT Industry. I learned the fundamentals of software developement and how to work with a team.",
    responsibilities: [],
    order: 5,
  },
  {
    slug: "it-instructor-cavite-state-university",
    title: "IT Instructor",
    company: "Cavite State University",
    location: "Cavite, PH",
    yearRange: "2014 - 2015",
    dateRange: "June 2014 - May 2015",
    description: "I worked as an IT instructor for two semesters at my alma mater. I primarily tought introductory computer subjects to first-year students and some intermediate courses to fourth-year students.",
    responsibilities: [],
    order: 6,
  },
  {
    slug: "freelance-software-developer-freelance",
    title: "Freelance Software Developer",
    company: "Freelance",
    location: "Cavite, PH",
    yearRange: "2014 - 2018",
    dateRange: "April 2014 - December 2018",
    description: "After graduating, I started to actively look for freelance projects and has been doing it part-time until 2018. This gave me opportunity to explore on different platforms such as mobile and IoT",
    responsibilities: [],
    order: 7,
  },
]
