import type { Project } from './types'

/**
 * Exported 1:1 from the Payload `projects` collection on 2026-09-12.
 *
 * REVIEW NEEDED — two known data-quality problems carried over from the CMS:
 *
 * 1. `type` is unreliable. Several entries marked "mobile" are not mobile apps
 *    (see the per-project REVIEW comments below). Nothing has been silently
 *    reclassified; fix these here and the whole site follows.
 * 2. `order` is not unique — five projects share order 1. Array order below is
 *    the CMS sort (order, then id). Renumber when the new work page is built.
 */
export const PROJECTS: Project[] = [
  {
    slug: "yuvee",
    title: "YuVee",
    description: "I worked as a full-stack developer on this project, working as the sole backend developer and front-end web developer. I also handled maintaining devops and deployment to AWS, introducing docker in deploying the new web application.",
    type: "web",
    tags: ["Laravel","NextJS","MySQL","Docker"],
    featured: false,
    personal: false,
    engine: "web",
    liveUrl: null,
    githubUrl: null,
    order: 1,
  },
  {
    slug: "reseebo",
    title: "Reseebo",
    description: "An offline-first personal project I started for my wife because we kept on losing our receipts.",
    type: "mobile",
    tags: ["React Native","Offline"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: "https://reseebo.vercel.app/",
    githubUrl: null,
    order: 1,
  },
  // REVIEW: no tags in the CMS — stack unknown, and type is "mobile".
  {
    slug: "win-win-ai",
    title: "WIN(win) AI",
    description: "AI Chat enabled mobile and web application. Used internally for NET(net) with they own data as knowledge base",
    type: "mobile",
    tags: [],
    featured: true,
    personal: false,
    engine: "claude",
    liveUrl: "https://ai.winwinit.com/",
    githubUrl: null,
    order: 1,
  },
  {
    slug: "finn-ai-ops",
    title: "Finn AI Ops",
    description: "The Leading AI Orchestration & Management Platform, Access the top AI engines—Anthropic (Claude), Google (Gemini), OpenAI (ChatGPT), xAI (Grok), and more—in one unified workspace. Finn AI's proprietary Automatic Intelligent Routing (AIR) algorithm optimizes every query for peak performance and up to 92% lower token costs, while delivering professional-grade organization, advanced filtering, and clear ROI visibility.",
    type: "web",
    tags: ["OpenRouter","AI","NextJS"],
    featured: false,
    personal: false,
    engine: "claude",
    liveUrl: "https://finnaiops.com/",
    githubUrl: null,
    order: 1,
  },
  {
    slug: "opic-nightlife-app",
    title: "OPIC - Nightlife App",
    description: "OPIC brings nightlife events, offers, bars, clubs, and venue discovery into one cinematic mobile-first experience.",
    type: "mobile",
    tags: ["React Native","NextJS"],
    featured: true,
    personal: false,
    engine: "native",
    liveUrl: "https://opic-app.com/",
    githubUrl: null,
    order: 1,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (ReactJS, Vite, ASP.NET, MSSQL) is not React Native.
  {
    slug: "real-time-rfid-registration",
    title: "Real-time RFID Registration",
    description: "I worked as full-stack developer on this project, working with a team. Appointment system for the company's customers to install their RFID Stickers to be used in the expressway Toll Systems.",
    type: "mobile",
    tags: ["ReactJS","Vite","ASP.NET","MSSQL"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 2,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (NextJS, ReactJS, Prisma, Clerk, Vercel, Generative AI, Vertex AI) is not React Native.
  {
    slug: "ai-persona-chat-bot",
    title: "AI Persona Chat Bot",
    description: "An AI Persona Chat Bot that helps you with specific topics the model is trained on. I worked solo on this project using the latest tech stack with NextJS and AI Technology",
    type: "mobile",
    tags: ["NextJS","ReactJS","Prisma","Clerk","Vercel","Generative AI","Vertex AI"],
    featured: true,
    personal: false,
    engine: "vertex",
    liveUrl: null,
    githubUrl: null,
    order: 3,
  },
  {
    slug: "saas-platform-mobile-application",
    title: "SaaS Platform Mobile Application",
    description: "I was lead front-end developer for this project, helped plan, design and setup initial back-end. This project is the mobile version of an existing SaaS Platform",
    type: "mobile",
    tags: ["React Native","PHP","Symfony","api-platform","PostgreSQL","MongoDB"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 4,
  },
  {
    slug: "plokernow",
    title: "PlokerNow",
    description: "A public web application for easily setting up a Planning Poker Session. This is a personal project",
    type: "web",
    tags: ["VueJS","Quasar","Firebase","Firestore"],
    featured: false,
    personal: false,
    engine: "web",
    liveUrl: null,
    githubUrl: null,
    order: 5,
  },
  {
    slug: "plant-tea-ta",
    title: "Plant Tea-ta",
    description: "Web Application for our local Milk Tea business. This serves as the POS System as well as inventory system and gives us sales analytics. I have a also integrated rewards systems for frequent buyers.",
    type: "web",
    tags: ["VueJS","Quasar","Firebase","Firestore"],
    featured: false,
    personal: false,
    engine: "web",
    liveUrl: null,
    githubUrl: null,
    order: 6,
  },
  {
    slug: "disguised-mari-web",
    title: "Disguised Mari Web",
    description: "Web Application of the Discord Bot for managing and updating recommendation data.",
    type: "web",
    tags: ["VueJS","AWS Api Gateway","AWS Lambda","DiscordJS","Heroku"],
    featured: false,
    personal: false,
    engine: "web",
    liveUrl: null,
    githubUrl: null,
    order: 7,
  },
  {
    slug: "disguised-mari-bot",
    title: "Disguised Mari Bot",
    description: "A Discord Bot I created for the game Grand Chase. This bot accepts commands and gives specific recommendations based on the user input.",
    type: "web",
    tags: ["NodeJS","AWS S3","Canvas","DiscordJS","Heroku"],
    featured: false,
    personal: false,
    engine: "web",
    liveUrl: null,
    githubUrl: null,
    order: 8,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (C#, Xamarin, Cross Platform) is not React Native.
  {
    slug: "shop-diggy",
    title: "Shop Diggy",
    description: "I worked as the front-end developer on this project, this is a mobile application to help users get the best deal from different e-commerce websites",
    type: "mobile",
    tags: ["C#","Xamarin","Cross Platform"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 9,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (C#, Xamarin, Cross Platform, Web API, ASP.NET, Google Maps) is not React Native.
  {
    slug: "tara-tracking-and-routing",
    title: "TARA: Tracking and Routing",
    description: "Tracking and routing application like Grab and Uber to reserve seats and view user location",
    type: "mobile",
    tags: ["C#","Xamarin","Cross Platform","Web API","ASP.NET","Google Maps"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 10,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (C#, Image Processing, EmguCV, WPF) is not React Native.
  {
    slug: "home-vision-face-recognition",
    title: "HOME VISION: Face Recognition",
    description: "Security system that uses face recognition to detect unrecognized persons entering the home",
    type: "mobile",
    tags: ["C#","Image Processing","EmguCV","WPF"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 11,
  },
  // REVIEW: typed "mobile" in the CMS but the stack (Raspberry Pi, C#, Web API, Google Maps, Windows 10 IoT) is not React Native.
  {
    slug: "halomet-voice-command-navigation-system",
    title: "HALOMET: Voice Command Navigation System",
    description: "A navigating system embedded on a helmet that utilizes speech recognition to navigate, including collision sensors.",
    type: "mobile",
    tags: ["Raspberry Pi","C#","Web API","Google Maps","Windows 10 IoT"],
    featured: false,
    personal: false,
    engine: "native",
    liveUrl: null,
    githubUrl: null,
    order: 12,
  },
]
