import type { Project } from './types'

/**
 * Re-classified from the Payload export (see `docs/build-plan.md` §2b) against the brief's
 * §7/§8 positioning. Descriptions, tags, and links are untouched — only `platform`,
 * `categories`, `mobileFramework`, `aiPlatform`, `personal`, and `repoStatus` were derived,
 * and only from the stack tags and each project's own description. Nothing invented.
 *
 * No project in the CMS ever carried a GitHub URL, so every `repoStatus` is `'unspecified'` —
 * absence of a link is not evidence of a private repo (§30), so nothing here claims
 * `'private-client'` without a URL to back it up either way.
 *
 * Ordered as `/work` displays it: React Native first, then full-stack/web, then the
 * non-mobile outliers last.
 */
export const PROJECTS: Project[] = [
  {
    slug: "win-win-ai",
    title: "WIN(win) AI",
    description: "AI-enabled chat application for mobile and web, built for internal use at NET(net) using their own data as the knowledge base.",
    platform: "mobile",
    categories: ["Mobile", "AI"],
    // No stack tags were ever recorded for this project — can't confirm React Native.
    mobileFramework: null,
    aiPlatform: "claude",
    tags: [],
    featured: true,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: "https://ai.winwinit.com/",
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 1,
  },
  {
    slug: "opic-nightlife-app",
    title: "OPIC - Nightlife App",
    description: "OPIC brings nightlife events, ticketing, table bookings, and venue discovery into one mobile-first experience, backed by a companion web dashboard venues use to manage their own events, offers, and staff.",
    platform: "mobile",
    categories: ["Mobile", "Full-Stack"],
    mobileFramework: "expo",
    aiPlatform: null,
    tags: ["React Native", "Expo", "Next.js", "Drizzle ORM", "Stripe"],
    featured: true,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: "https://opic-app.com/",
    githubUrl: null,
    images: [],
    logoUrl: "/images/opic-icon.png",
    order: 2,
  },
  {
    slug: "saas-platform-mobile-application",
    title: "SaaS Platform Mobile Application",
    description: "Led front-end development for the mobile version of an existing SaaS platform, and helped plan, design, and set up the initial back-end.",
    platform: "mobile",
    categories: ["Mobile", "SaaS", "Full-Stack"],
    mobileFramework: "react-native",
    aiPlatform: null,
    tags: ["React Native","PHP","Symfony","api-platform","PostgreSQL","MongoDB"],
    featured: true,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 3,
  },
  {
    slug: "reseebo",
    title: "Resiboo",
    description: "An offline-first receipt scanner I started for my wife because we kept losing our receipts. Scan a receipt and Resiboo reads the merchant, total, and every line item, then files it for later — no account, no cloud required.",
    platform: "mobile",
    categories: ["Mobile"],
    mobileFramework: "expo",
    aiPlatform: null,
    tags: ["React Native", "Expo", "Drizzle ORM", "Offline-first"],
    featured: true,
    // "a personal project I started for my wife"
    personal: true,
    repoStatus: "unspecified",
    liveUrl: "https://www.resiboo.com/",
    githubUrl: null,
    images: [],
    logoUrl: "/images/resiboo-icon.png",
    order: 4,
  },
  {
    slug: "finn-ai-ops",
    title: "Finn AI",
    description: "An organization-level AI chat platform: folder-based conversation organization, model-tier selection across multiple LLM providers via OpenRouter, a pre-flight filter classifier for governance, and an admin analytics dashboard for org owners.",
    platform: "web",
    categories: ["Web", "AI", "SaaS"],
    mobileFramework: null,
    aiPlatform: "openrouter",
    tags: ["Next.js", "Payload CMS", "OpenRouter", "Vercel AI SDK", "Stripe"],
    featured: true,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: "https://app.finnaiops.com/",
    githubUrl: null,
    images: [],
    logoUrl: "/images/finn-icon.png",
    order: 5,
  },
  {
    slug: "ai-persona-chat-bot",
    title: "AI Persona Chat Bot",
    description: "An AI persona chat bot for topic-specific conversations, built solo with Next.js and generative AI.",
    // Was "mobile" + featured in the CMS; the stack (NextJS, ReactJS, Prisma, Clerk,
    // Vercel, Generative AI, Vertex AI) is a web app, not React Native.
    platform: "web",
    categories: ["Web", "AI", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: "vertex",
    tags: ["NextJS","ReactJS","Prisma","Clerk","Vercel","Generative AI","Vertex AI"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 6,
  },
  {
    slug: "yuvee",
    title: "YuVee",
    description: "Sole full-stack developer on this project, owning both the backend and front-end. Also managed DevOps and AWS deployment, introducing Docker for the new web application.",
    platform: "web",
    categories: ["Web", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["Laravel","NextJS","MySQL","Docker"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 7,
  },
  {
    slug: "real-time-rfid-registration",
    title: "Real-time RFID Registration",
    description: "Full-stack developer on a team building an appointment system for customers to install RFID stickers used in expressway toll systems.",
    // Was "mobile" in the CMS; the stack (ReactJS, Vite, ASP.NET, MSSQL) is a web app.
    platform: "web",
    categories: ["Web", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["ReactJS","Vite","ASP.NET","MSSQL"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 8,
  },
  {
    slug: "plant-tea-ta",
    title: "Plant Tea-ta",
    description: "Web application for a local milk tea business, serving as the POS and inventory system with built-in sales analytics and a rewards program for frequent buyers.",
    platform: "web",
    categories: ["Web", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["VueJS","Quasar","Firebase","Firestore"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 9,
  },
  {
    slug: "tara-tracking-and-routing",
    title: "TARA: Tracking and Routing",
    description: "Ride-hailing style tracking and routing application, similar to Grab or Uber, for reserving seats and viewing real-time user location.",
    platform: "mobile",
    categories: ["Mobile", "Full-Stack"],
    // Was engine `native`, which rendered as "React Native" — the stack (C#, Xamarin) is not.
    mobileFramework: "xamarin",
    aiPlatform: null,
    tags: ["C#","Xamarin","Cross Platform","Web API","ASP.NET","Google Maps"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 10,
  },
  {
    slug: "shop-diggy",
    title: "Shop Diggy",
    description: "Front-end developer on a mobile application that helps users compare deals across different e-commerce websites.",
    platform: "mobile",
    categories: ["Mobile"],
    mobileFramework: "xamarin",
    aiPlatform: null,
    tags: ["C#","Xamarin","Cross Platform"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 11,
  },
  {
    slug: "plokernow",
    title: "PlokerNow",
    description: "A public web application for quickly setting up Planning Poker sessions. Personal project.",
    platform: "web",
    categories: ["Web"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["VueJS","Quasar","Firebase","Firestore"],
    featured: false,
    // "This is a personal project"
    personal: true,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 12,
  },
  {
    slug: "disguised-mari-web",
    title: "Disguised Mari Web",
    description: "Web application for the Discord bot, used to manage and update its recommendation data.",
    platform: "web",
    categories: ["Web", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["VueJS","AWS Api Gateway","AWS Lambda","DiscordJS","Heroku"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 13,
  },
  {
    slug: "disguised-mari-bot",
    title: "Disguised Mari Bot",
    description: "A Discord bot built for the game Grand Chase, providing tailored recommendations based on user commands.",
    platform: "web",
    categories: ["Web", "Full-Stack"],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["NodeJS","AWS S3","Canvas","DiscordJS","Heroku"],
    featured: false,
    // "a Discord Bot I created"
    personal: true,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 14,
  },
  {
    slug: "home-vision-face-recognition",
    title: "HOME VISION: Face Recognition",
    description: "Home security system that uses face recognition to detect unrecognized individuals entering the premises.",
    // Was "mobile" in the CMS; the stack (C#, EmguCV, WPF) is a Windows desktop app.
    platform: "desktop",
    categories: [],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["C#","Image Processing","EmguCV","WPF"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 15,
  },
  {
    slug: "halomet-voice-command-navigation-system",
    title: "HALOMET: Voice Command Navigation System",
    description: "A helmet-embedded navigation system using speech recognition for hands-free navigation, with collision sensors for added safety.",
    // Was "mobile" in the CMS; Raspberry Pi + Windows 10 IoT is an embedded device, not a phone.
    platform: "iot",
    categories: [],
    mobileFramework: null,
    aiPlatform: null,
    tags: ["Raspberry Pi","C#","Web API","Google Maps","Windows 10 IoT"],
    featured: false,
    personal: false,
    repoStatus: "unspecified",
    liveUrl: null,
    githubUrl: null,
    images: [],
    logoUrl: null,
    order: 16,
  },
  {
    slug: "stratos-command",
    title: "Stratos Command",
    description: "A multi-tenant B2B SaaS starter kit: organizations, invitations, and SSO/SAML via Better Auth, a Payload CMS backend, Stripe billing, audit logs, and an AI-powered support chat (Stratos Support) built on OpenRouter — forked and rebranded as the foundation for new products.",
    platform: "web",
    categories: ["Web", "Full-Stack", "AI", "SaaS"],
    mobileFramework: null,
    aiPlatform: "openrouter",
    tags: ["Next.js", "Payload CMS", "Better Auth", "Stripe", "OpenRouter"],
    featured: true,
    // A self-directed starter kit, not client work.
    personal: true,
    repoStatus: "unspecified",
    liveUrl: "https://app.stratoscommand.com/",
    githubUrl: null,
    images: [],
    logoUrl: "/images/stratos-icon.png",
    order: 17,
  },
]

/** §7 priority-1 pool: genuinely React Native/Expo work, enforced by data rather than by
 * every component remembering to filter for it. */
export const REACT_NATIVE_PROJECTS: Project[] = PROJECTS.filter(
  (p) => p.mobileFramework === "react-native" || p.mobileFramework === "expo"
)
